defaults:
  - view_sampler: bounded

name: re10k_test
roots: [/mnt/data4/dl3dv-3k4k/dl3dv_benchmark]
make_baseline_1: true
augment: false
image_shape: [180, 320] 
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: -1.
far: -1.
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
test_chunk_interval: 1